// Database of words for Mimic.
// Each entry: { word: string, category: "P" | "O" | "A" | "D" | "L" | "T", allPlay: boolean }
//
// Categories:
//   P = Pessoa, Lugar ou Animal
//   O = Objeto
//   A = Ação
//   D = Difícil
//   L = Lazer
//   T = Todos jogam (sempre allPlay)
//
// allPlay = true means every team plays at the same time
// (T category words OR words marked with * in the source).
//
// Words extracted via OCR from the original cards.
// Please report typos or mis-transcribed entries.

(function () {
  // Compact form: [word, category, allPlay?]
  // allPlay defaults to true when category is "T".
  const RAW = [
    // --- Batch 1 ---
    ["rainha","P"],["veleiro","O"],["falar com a parede","A"],["indignado","D"],["Dustin Hoffman","L"],["grito","T"],
    ["simpático","P"],["panetone","O",1],["pulverizar","A"],["pediatra","D",1],["\"Sonhos de uma Noite de Verão\"","L"],["domingo","T"],
    ["narrador","P"],["trepadeira","O"],["castigar","A"],["rabo-de-saia","D"],["tiro de partida","L"],["vírgula","T"],
    ["crista","P",1],["canoa","O"],["picotar","A"],["imediato","D"],["buraco (jogo)","L"],["luminária","T"],
    ["bicho","P",1],["bobina","O",1],["serrar","A",1],["valor","D",1],["\"Mad\" (revista)","L",1],["bóton","T"],
    ["senzala","P"],["entulho","O"],["cometer suicídio","A"],["vago","D"],["\"Robocop\"","L"],["nazismo","T"],
    ["caranguejo","P"],["guarda-sol","O"],["ajudar","A"],["lacuna","D"],["aplausos","L"],["insulto","T"],
    ["médico","P",1],["discos","O",1],["adoecer","A",1],["atentado ao pudor","D",1],["Manoel Bandeira","L",1],["letra","T"],
    ["vírus","P",1],["camafeu","O",1],["amassar","A",1],["desafogado","D",1],["goleada","L",1],["população","T"],
    ["Isaac Newton","P"],["pingente","O"],["florescer","A"],["magma","D"],["gibi","L"],["bombeiro","T"],
    ["físico (profissão)","P"],["tinteiro","O"],["ninar","A"],["adultério","D"],["tabelar (futebol)","L"],["pêra","T"],
    ["ratazana","P",1],["dicionário","O",1],["desbastar","A",1],["eremita","D",1],["\"Se Meu Fusca Falasse\"","L",1],["névoa","T"],
    ["testemunha","P"],["assoalho","O"],["intercalar","A"],["mortalha","D"],["\"Fantasia\"","L"],["girassol","T"],
    ["osso","P"],["tecido estampado","O"],["poluir","A"],["bacilo","D"],["\"encurralado\"","L"],["radiografia","T"],
    ["mamífero","P"],["pompom","O"],["tirar o escalpo","A"],["sebo","D"],["Irmãos Metralha","L"],["pepino","T"],
    ["contorcionista","P"],["margarina","O"],["redigir","A"],["carrasco","D"],["pit stop","L"],["furacão","T"],
    ["nádega","P",1],["sutiã","O",1],["apresentar","A",1],["autopsia","D",1],["\"O Dólar Furado\"","L",1],["alarme de carro","T"],
    ["criança","P"],["brigadeiro (doce)","O"],["sacudir","A"],["inocente","D"],["futebol de botão","L"],["lancha","T"],
    ["padre","P"],["carrinho de feira","O"],["escorregar","A"],["psicologia","D"],["\"Irmãos Coragem\"","L"],["semana","T"],
    ["anão","P"],["trabuco","O"],["brincar","A"],["bucha","D"],["Hortênsia","L"],["perspectiva","T"],
    ["sofá","P"],["catchup","O"],["acertar no alvo","A"],["primavera","D"],["\"Perdidos no Espaço\"","L"],["foto","T"],
    ["fugitivo","P"],["suporte de plantas","O"],["movimentar","A"],["noturno","D"],["play-ground","L"],["tapa","T"],
    ["garçom","P"],["orelha de livro","O"],["nascer","A"],["correção monetária","D"],["bater figurinha","L"],["relâmpago","T"],
    ["arrepio","P",1],["chá","O",1],["ter um caso","A",1],["patente (de porta)","D",1],["Chico Buarque","L",1],["tangente","T"],
    ["manhosa","P",1],["faca elétrica","O",1],["apanhar","A",1],["saudável","D",1],["\"O Barbeiro de Sevilha\"","L",1],["cócegas","T"],
    ["barata","P"],["mesa de bilhar","O"],["pagar","A"],["diagnóstico","D"],["amarelinha","L",1],["labareda","T"],
    ["México","P"],["minissaia","O"],["acompanhar","A"],["botão de emergência","D",1],["carambola","L"],["laranja","T"],
    ["Salvador","P",1],["filtro","O"],["chorar","A",1],["harmonia","D"],["Colombina","L",1],["itinerário","T"],
    ["tímpano","P"],["amuleto","O"],["abrir a porta","A"],["válvula","D"],["show","L",1],["peso","T"],
    ["Júlio César","P",1],["motocicleta","O",1],["atracar","A",1],["quarentena","D",1],["cara-ou-coroa","L",1],["elétron","T"],
    ["Leonardo da Vinci","P"],["pavio","O"],["emergir","A"],["valente","D"],["Magic Johnson","L"],["relinchar","T"],
    ["mulato","P",1],["walk machine","O",1],["fazer as pazes","A",1],["larva","D",1],["zape","L",1],["cartaz","T"],
    ["corvo","P"],["sacola de feira","O"],["amamentar","A"],["gula","D"],["\"As 7 Vampiras\"","L"],["juros","T"],
    ["Fernando Collor de Mello","P"],["papel picado","O"],["examinar","A"],["alienação","D"],["Gal Costa","L"],["Corão","T"],
    ["topete","P",1],["poltrona","O",1],["desmatar","A",1],["pterodáctilo","D",1],["Mozart","L",1],["caqui","T"],
    ["enxame de abelhas","P"],["porta-malas","O"],["marcar","A"],["ocioso","D"],["\"O Homem Elefante\"","L"],["guaraná","T"],
    ["feminino","P"],["sino","O"],["cancelar","A"],["jóquei","D"],["fã-clube","L"],["velório","T"],
    ["Santos Dumont","P"],["medalha","O"],["atirar","A"],["vingamento","D"],["\"Janela Indiscreta\"","L"],["tom","T"],
    ["idade","P",1],["corneta","O",1],["descarçar","A",1],["fio de bigode","D",1],["churrasco","L",1],["casca","T"],
    ["lanterninha","P",1],["placa de proibido estacionar","O",1],["coleatar","A",1],["estrabismo","D",1],["medalha de ouro","L",1],["esquadro","T"],
    ["calvo","P"],["gaiola","O"],["coar","A"],["maremoto","D"],["cama-de-gato","L"],["amortecedor (de automóvel)","T"],
    ["gueixa","P"],["anágua","O"],["cerrar as pálpebras","A"],["algemas","D"],["desenho animado","L"],["pastel","T"],
    ["tarado","P"],["xarope","O"],["trair","A"],["fanático","D"],["ator","L"],["escafandro","T"],
    ["pesada","P"],["espectro de luz","O"],["estudar","A"],["haste","D"],["Capitão Gancho","L"],["parto","T"],
    ["empregada","P",1],["panela de pressão","O",1],["amamentar","A",1],["galanteador","D",1],["Mafalda","L",1],["programa","T"],
    ["litoral","P"],["limpador de pára-brisas","O"],["andar a cavalo","A"],["legítimo","D"],["\"Pink Floyd\"","L",1],["hepatite","T"],
    ["leve","P",1],["tonel","O"],["fazer a barba","A",1],["simpatia","D"],["Telê Santana","L",1],["parábola","T"],
    ["Palácio do Planalto","P",1],["bisturi","O",1],["acorrentar","A",1],["chantagem","D",1],["Ney Matogrosso","L",1],["cerveja","T"],
    ["pica-pau","P"],["terço","O"],["sufritar","A"],["gabinete","D"],["João Bafo-de-Onça","L"],["interfone","T"],
    ["normal","P",1],["micro-ônibus","O",1],["demarcar","A",1],["haxixe","D",1],["partitura","L",1],["velocidade","T"],
    ["estatura","P"],["canudo","O"],["despir","A"],["repressão","D"],["teatro de fantoches","L"],["casaco","T"],
    ["floresta","P"],["crucifixo","O"],["deslocar","A"],["consórcio","D"],["\"Missão Impossível\"","L"],["chácara","T"],
    ["sábio","P",1],["bibelô","O"],["bloquear","A",1],["plantão","D"],["pião","L",1],["sanduíche","T"],
    ["mergulhador","P"],["lenço","O"],["guiar um cego","A"],["enchimento","D"],["Palmeiras","L"],["rebote","T"],
    ["Maquiavel","P",1],["galho","O",1],["aderir","A",1],["incerteza","D",1],["Sivuca","L",1],["redação","T"],
    ["albino","P"],["carta de amor","O",1],["depilar","A"],["caboclo","D"],["Zico","L"],["neon","T"],
    ["cheiroso","P"],["trava","O"],["desarmar","A"],["garupa","D"],["numismática","L"],["Concorde (avião)","T"],
    ["orfanato","P"],["aspirina","O"],["estender roupa","A"],["vértice","D"],["diretor de cinema","L"],["par","T"],
    ["mundo","P"],["apagador","O"],["lascar","A"],["fechar a 7 chaves","D"],["\"Corrida Maluca\"","L"],["papiro","T"],
    ["George Bush","P",1],["jaula","O",1],["preparar","A",1],["indexar","D",1],["\"Crocodilo Dundee\"","L",1],["caçamba","T"],
    ["Argentina","P"],["chicote","O"],["cumprimentar","A"],["natimorto","D"],["\"Led Zeppelin\"","L"],["missa","T"],
    ["xereta","P"],["torta de morango","O"],["derrubar","A"],["calo","D"],["\"Os Pássaros\"","L"],["corado","T"],
    ["esponja-do-mar","P"],["balança de farmácia","O"],["abastecer","A"],["papa-defuntos","D"],["Gugu Liberato","L"],["ouro","T"],
    ["inferno","P"],["bomba de gasolina","O"],["dar a volta ao mundo","A"],["atmosfera","D"],["ritmo","L"],["sexo","T"],
    ["mula","P",1],["ovo estalado","O",1],["fazer as malas","A",1],["conversão","D",1],["trenzinho elétrico","L",1],["ziguezague","T"],
    ["canguru","P"],["atadura","O"],["obturar","A",1],["gastronomia","D",1],["maestro","L"],["passe","T"],
    ["nobre","P"],["táxi","O"],["enfeitar","A"],["laser","D"],["par de damas","L"],["produção","T"],
    ["Tietê (rio)","P"],["leme","O"],["torturar","A"],["alimentar","D"],["Carmen Miranda","L"],["lua crescente","T"],
    ["faminto","P"],["porta-retrato","O"],["zeloso","A"],["\"Oktoberfest\"","D"],["turbina","T"],
    ["detetive","P",1],["gatinho","O",1],["arborizar","A",1],["beija-flor","D",1],["Senha (jogo)","L",1],["grama","T"],
    ["leão","P"],["ferro de passar","O"],["triturar","A"],["gaúcho","D"],["bandeirinha","L"],["meteorologia","T"],
    ["fonte","P"],["gargantilha","O"],["fechar","A"],["sinceridade","D"],["Chitãozinho e Xororó","L"],["página","T"],
    ["ganso","P"],["caixa de fósforos","O"],["tosar","A"],["busca","D"],["Miéle","L"],["salina","T"],
    ["playground","P"],["biombo","O"],["brotar","A"],["turma","D"],["Bob Marley","L"],["político","T"],
    ["Zerbini","P",1],["planetário","O",1],["calibrar pneus","A",1],["vacilar","D",1],["Dick Tracy","L",1],["plataforma","T"],

    // --- Batch 2 ---
    ["nora","P",1],["pulôver","O"],["agulhar","A"],["sequestro","D"],["\"Danúbio Azul\"","L"],["revista","T"],
    ["formiga","P",1],["lata de biscoito","O"],["afastar","A"],["juramento","D"],["luta na lama","L",1],["rubi","T"],
    ["bica","P"],["busto","O"],["folheto","A"],["botar ovos","D"],["valete de paus","L"],["gravidade","T"],
    ["bigodes (de gato)","P",1],["saleiro","O"],["apedrejar","A"],["pelego","D"],["coleção","L"],["sabicha","T"],
    ["triste","P",1],["dedilhar","O"],["LSD","A"],["\"Na Cama com Madonna\"","D"],["arroz","L"],["sabiá","T"],
    ["sensual","P",1],["tijoira","O"],["consertar","A"],["faxina","D"],["cruzeiro marítimo","L",1],["jabuticaba","T"],
    ["namorados","P",1],["papel higiênico","O",1],["tremer","A"],["defeito","D"],["can-can","L"],["química","T"],
    ["cromossomo","P",1],["orelhão","O",1],["pisar no tomate","A"],["entrega","D"],["Pavarotti","L",1],["libélula","T"],
    ["Havana","P",1],["estola","O"],["fundir (motor)","A",1],["fantástico","D"],["dama de copas","L",1],["travessão","T"],
    ["corno","P",1],["véu de noiva","O",1],["asfaltar","A"],["ignição","D"],["corrida de cavalos","L",1],["batalhão","T"],
    ["caolho","P"],["escorredor de macarrão","O"],["correr atrás","A"],["pesadelo","D"],["Regina Duarte","L"],["calmante","T"],
    ["leiloeiro","P",1],["pêssego","O"],["compor","A"],["gênio","D"],["Haggar, o Horrível","L"],["Marinha","T"],
    ["tonto","P",1],["saxofone","O"],["escolher","A"],["narcótico","D"],["hobby","L",1],["paçoca","T"],
    ["duna","P",1],["carretilha","O"],["cozinhar","A"],["herança","D"],["atriz","L"],["frasqueira","T"],
    ["memória","P",1],["conservas","O"],["acasalar","A"],["zona","D"],["pulgas amestradas","L",1],["multa","T"],
    ["cachoeira","P"],["chocolate","O"],["atravessar a rua","A"],["escrivão","D"],["Adoniran Barbosa","L"],["rotativa","T"],
    ["terraço","P",1],["alto-falante","O",1],["maquilar","A"],["dor de dentes","D"],["António Fagundes","L"],["gargalo","T"],
    ["observatório","P",1],["caminhão-tanque","O"],["beber","A"],["zombaria","D"],["pescaria","L"],["empada","T"],
    ["professor","P",1],["trevo","O",1],["destelhar","A"],["ter uma idéia","D"],["\"Sansão e Dalila\"","L"],["placar","T"],
    ["peru","P",1],["cortador de grama","O"],["neurótico","A",1],["canonizar","D"],["\"A Noviça Rebelde\"","L",1],["verão","T"],
    ["míope","P",1],["persiana","O"],["engatinhar","A"],["feio","D"],["noite de autógrafos","L",1],["partido","T"],
    ["cigana","P",1],["novelo","O"],["untar","A"],["cesto de roupa suja","D"],["musculação","L",1],["iogurte","T"],
    ["rebanho","P",1],["mola","O"],["dirigir","A"],["mitologia","D"],["marionetes","L"],["IBM","T"],
    ["Himalaia","P",1],["fivela","O"],["simular","A",1],["civilização","D"],["tia Anastácia","L"],["pilha","T"],
    ["máscara","P",1],["bateria de automóvel","O",1],["esburacar","A"],["câmbio negro","D"],["\"Cidadão Kane\"","L"],["poligamia","T"],
    ["roedor","P",1],["cadeira giratória","O"],["pisar na bola","A"],["sorriso amarelo","D"],["tenor","L"],["torpedo","T"],
    ["Napoleão Bonaparte","P",1],["saia plissada","O"],["escalar","A"],["quadriculado","D"],["música country","L"],["vacina","T"],
    ["Chile","P",1],["sirene","O"],["juntar","A",1],["insígnia","D"],["drible","L"],["artesanato","T"],
    ["matilha","P",1],["bagageiro","O"],["orar","A"],["coragem","D"],["drama","L"],["tubulação","T"],
    ["imaculada","P",1],["barril de chope","O"],["embaçar","A"],["abóbada","D"],["\"A Família Trapo\"","L"],["geléia","T"],
    ["jurado","P"],["ovos de Páscoa","O"],["buzinar","A"],["universo","D"],["ganhar o jogo","L"],["fraldas","T"],
    ["mendigo","P"],["botão de camisa","O"],["dar uma tacada","A"],["holografia","D"],["Zé Colméia","L",1],["vitrine","T"],
    ["Sócrates","P",1],["absorvente","O"],["refazer","A"],["investimento","D"],["jóquei","L"],["morte","T"],
    ["vítela","P",1],["comprimidos","O"],["arrumar","A"],["arranha-céus","D"],["arlequim","L"],["cartão de ponto","T"],
    ["Cristóvão Colombo","P",1],["furador de papel","O"],["ouvir rádio","A"],["miúdos","D"],["heavy metal","L",1],["taco","T"],
    ["coxo","P",1],["remo","O"],["alfabetizar","A",1],["traição","D"],["Fla-Flu","L"],["onda","T"],
    ["masculino","P",1],["chupeta","O",1],["caminhar","A"],["fetichismo","D"],["jardinagem","L"],["procissão","T"],
    ["ocidente","P",1],["corrente","O"],["bater continência","A"],["lantejoula","D"],["\"Chaves\"","L"],["processo","T"],
    ["traseira","P",1],["colarinho","O"],["agrupar","A"],["susto","D"],["São Paulo Futebol Clube","L"],["trilho de trem","T"],
    ["fogosa","P",1],["sela","O"],["sair","A"],["umbilical","D"],["xilofone","L"],["hipotenusa","T"],
    ["cão","P"],["lápide","O"],["quebrar","A"],["direito","D"],["picadeiro","L"],["silêncio","T"],
    ["\"Sem teto\"","P",1],["posto de gasolina","O"],["furar","A"],["guerrilha","D"],["salto em altura","L"],["quarto","T"],
    ["digitador","P",1],["piso","O"],["inflamar","A"],["crueldade","D"],["trapezista","L"],["tradução","T"],
    ["cigarra","P",1],["horta","O"],["agredir","A"],["departamento","D"],["cartomante","L"],["ocaso","T"],
    ["mulher","P",1],["boina","O"],["derrapar","A"],["remorso","D"],["\"João e o Pé de Feijão\"","L"],["presente","T"],
    ["grilo","P",1],["cortador de unha","O"],["borbulhar","A"],["hipocondríaco","D"],["\"A Moreninha\"","L"],["pântano","T"],
    ["bronzeado","P",1],["viseira","O"],["acordar","A"],["agente","D"],["Henfil","L"],["leite","T"],
    ["hidroelétrica","P",1],["cachepô","O"],["enterrar","A"],["anestesia","D"],["\"Vestida Para Matar\"","L"],["jantar","T"],
    ["pena","P",1],["espartilho","O"],["esticar","A"],["caipira","D"],["batuta","L"],["processo","T"],
    ["solteira","P",1],["torre","O"],["carimbar","A"],["desempregado","D"],["feijões saltadores","L"],["trovão","T"],
    ["língua","P",1],["torradeira","O"],["circular","A"],["soro","D"],["Carlos Zéfiro","L"],["Xerox","T"],
    ["matagal","P",1],["misto quente","O"],["sintonizar","A"],["asilo","D"],["Geraldão","L"],["corpete","T"],
    ["suspeito","P",1],["prateleira","O"],["lustrar sapatos","A"],["cratera","D"],["jet-ski","L"],["ultra-sonografia","T"],
    ["cardume","P",1],["buraco de fechadura","O"],["cacarejar","A"],["liquidação","D"],["Hulk","L"],["extraterrestre","T"],
    ["família","P",1],["espanador","O"],["ultrapassar","A"],["rente","D"],["espetáculo","L"],["temperatura","T"],
    ["surdo","P"],["broxa","O"],["afanar","A"],["abismo","D"],["\"A Profecia\"","L"],["paletó","T"],
    ["feiticeira","P"],["talão de cheques","O"],["cheirar o copinho","A"],["cassete","D"],["Peninha","L"],["gota","T"],
    ["frade","P"],["apontador de lápis","O"],["assoprar","A"],["horror","D"],["ventríloquo","L"],["paixão","T"],
    ["François Mitterrand","P",1],["revólver","O"],["rolar","A"],["domicílio","D"],["corrida de karts","L"],["batalha","T"],
    ["miado","P",1],["soquete","O"],["desenrolar","A"],["aborto","D"],["\"Expresso da Meia-Noite\"","L"],["farol","T"],
    ["irritado","P",1],["galheteiro","O"],["acender","A"],["filete","D"],["\"Dança com Lobos\"","L"],["zodíaco","T"],
    ["Netuno","P",1],["bate-estaca","O"],["amansar","A"],["nasal","D"],["\"O Fantasma da Ópera\"","L"],["trouxa","T"],
    ["mesquita","P",1],["triângulo","O"],["descobrir","A"],["aposentadoria","D"],["Elvis Presley","L"],["passarela","T"],
    ["vestida","P",1],["planar","O"],["meia-entrada","A"],["farpa","D"],["Charlie Brown","L"],["raios-X","T"],
    ["sexy","P",1],["cabeça de alho","O"],["pingar","A"],["cadarço","D"],["TV a cabo","L"],["cuco (pássaro)","T"],
    ["gamba","P",1],["árvore de Natal","O",1],["desligar","A"],["macumba","D"],["Louis Armstrong","L"],["marca","T"],
    ["trabalhador","P",1],["pergaminho","O"],["atingir","A"],["retina","D"],["platéia","L"],["sorvete","T"],
    ["planalto","P",1],["travessa","O"],["abarrotar","A"],["guichê","D"],["damas","L"],["câimbra","T"],
    ["carvoeiro","P",1],["bloco (de papel)","O"],["\"cair fora\"","A",1],["bochechar","D"],["\"Império dos Sentidos\"","L"],["Congresso","T"],
    ["imbecil","P",1],["figa","O"],["queimar o cartucho","A"],["quilômetro","D",1],["\"9 1/2 Semanas de Amor\"","L"],["eletricidade","T"],
    ["macho","P",1],["porta-guardanapo","O"],["correr","A"],["gago","D"],["apito final","L"],["talismã","T"],
    ["Ilha do Mel","P",1],["mamadeira","O"],["chacoalhar","A"],["aguardente","D"],["ikebana","L"],["isca","T"],
    ["bonito","P",1],["alcachofra","O"],["enquadrar","A"],["encosto","D"],["Alain Prost","L"],["ladrilho","T"],
    ["África do Sul","P",1],["viaduto","O"],["espinar","A"],["jornada","D"],["\"Globo Repórter\"","L"],["Colosso de Rodes","T"],
    ["Sigmund Freud","P",1],["cigarro","O"],["denunciar","A"],["talento","D"],["Ray Charles","L"],["corte","T"],

    // --- Batch 3 ---
    ["Ronald Reagan","P",1],["aro de bicicleta","O"],["desenhar","A"],["crise","D"],["horóscopo","L"],["mar","T"],
    ["iceberg","P",1],["porta-jóias","O"],["pressionar (botão)","A"],["paiol","D"],["pódio","L"],["vaivém","T"],
    ["bar","P",1],["camisa","O"],["apagar","A"],["pia","D"],["pega-pega","L"],["caixa-postal","T"],
    ["banguela","P"],["dial","O"],["enfiesar","A"],["quibumbo","D"],["Nigel Mansell","L"],["picadinho","T"],
    ["gente","P",1],["ramalhete","O",1],["embedecar-se","A",1],["símbolo","D",1],["teclado","L",1],["sílaba","T"],
    ["lagoa","P"],["recheio","O"],["abocanhar","A"],["vanguarda","D"],["filme","L"],["toque","T"],
    ["inca","P",1],["tuba","O"],["grudar","A"],["pá de ventilador","D"],["advogado","L"],["língua-de-sogra","T"],
    ["Dinamarca","P",1],["hóstia","O"],["discar","A"],["tecnologia","D"],["Professor Pardal","L"],["galeão","T"],
    ["oculista","P",1],["gravata","O"],["fatiar","A"],["Janis Joplin","D"],["Paleta","L"],["janeiro","T"],
    ["bêbado","P",1],["bule","O",1],["provar","A",1],["destino","D",1],["palestra","L",1],["piquete","T"],
    ["anjo","P"],["serpentina","O"],["brindar","A"],["reencarnação","D"],["paciência (de cartas)","L"],["dor-de-cotovelo","T"],
    ["abafado","P",1],["condicionador de ar","O"],["dar","A"],["calote","D"],["Pluto","L"],["coturno","T"],
    ["líquido","P",1],["esparramar","O"],["talher de peixe","A"],["\"20 Mil Léguas Submarinas\"","D"],["Três Reis Magos","L"],["sonho","T"],
    ["galo","P",1],["dentifrício","O"],["olho no espelho","A"],["profundo","D"],["clave de sol","L"],["sonho","T"],
    ["japonês","P",1],["agudo","O",1],["desbloquear","A",1],["intrometido","D",1],["\"Tirando a Casa pra Mãe Joana\"","L",1],["isopor","T"],
    ["gay","P"],["calota","O"],["amar","A"],["macabro","D"],["ping-pong","L"],["ultra-som","T"],
    ["padeiro","P",1],["bolha de sabão","O"],["dar no pé","A"],["ferida","D"],["gol","L"],["Airton Senna","T"],
    ["senha (código)","P"],["crina","O",1],["régua","A"],["armar","D"],["poesia","L"],["hino","T"],
    ["juiz","P",1],["bazuca","O"],["afagar","A"],["debate","D"],["\"Rin-tin-tin\"","L"],["pisca-pisca","T"],
    ["coitado","P",1],["xícara","O",1],["espremer","A",1],["antena parabólica","D",1],["paint ball","L",1],["mesa","T"],
    ["menino","P"],["fichário","O"],["adoçar","A"],["bodas de prata","D"],["\"Carmen\"","L"],["kit","T"],
    ["timoneiro","P",1],["retrós (de linha)","O"],["aglomerar","A"],["judiciário","D"],["strip-tease","L"],["mensagem","T"],
    ["carne","P",1],["capa de chuva","O"],["filar um cigarro","A"],["papelão","D"],["cochechia","L"],["madrugada","T"],
    ["cabelo grisalho","P",1],["cardápio","O"],["picar","A"],["cascalho","D"],["Música Popular Brasileira","L"],["sacola","T"],
    ["Platão","P",1],["bandeirinha de São João","O",1],["redor","A",1],["membrana","D",1],["\"Cabaret\"","L",1],["greve","T"],
    ["cunhada","P",1],["maçaneta","O"],["avançar","A"],["iguaria","D"],["\"Kama Sutra\"","L"],["levitação","T"],
    ["coluna vertebral","P",1],["liquidificador","O"],["dançar","A"],["polígono","D"],["escultura","L"],["pivô","T"],
    ["jagunço","P",1],["riacho","O",1],["ajoelhar","A",1],["lampião","D",1],["Tim Maia","L",1],["aquário (de peixes)","T"],
    ["porão","P",1],["criado-mudo","O"],["catequizar","A"],["naftalina","D"],["\"Deus e o Diabo na Terra do Sol\"","L"],["chapa","T"],
    ["Fidel Castro","P",1],["droga","O"],["ensaboar","A"],["argamassa","D"],["caçar borboletas","L"],["sussurrar","T"],
    ["racista","P",1],["canivete","O"],["aquíçar","A"],["vitamina","D"],["montanha-russa","L"],["sinal da cruz","T"],
    ["frente","P",1],["griffe","O"],["temperar","A"],["capilar","D"],["sambada","L"],["licor","T"],
    ["pensão","P",1],["caixa registradora","O"],["sacudir","A"],["bombada","D"],["música clássica","L"],["trigo","T"],
    ["operário","P",1],["semáforo","O"],["calar","A"],["manjedoura","D"],["jogo do bicho","L"],["mimeógrafo","T"],
    ["cascavel","P",1],["capacete","O",1],["reger","A",1],["chaga","D",1],["boxe","L",1],["ruxo","T"],
    ["lontra","P",1],["sanfona","O"],["ficar de molho","A"],["mancebo","D"],["Cascão","L"],["Júlio Verne","T"],
    ["Amazonas","P",1],["batina","O"],["abater","A"],["milionário","D"],["pula-pula","L"],["ultra-leve","T"],
    ["anticorpo","P",1],["coador de café","O"],["avizinhar","A"],["bicarquixa","D"],["Roberto Carlos","L"],["cacau","T"],
    ["paciente","P",1],["escumadeira","O"],["tatear","A"],["vontade","D"],["\"Sexta-Feira 13\"","L"],["madeira","T"],
    ["nacionalista","P",1],["batedeira","O",1],["amarrar","A",1],["ensaio","D",1],["bossa nova","L",1],["tumor","T"],
    ["arara","P"],["açucareiro","O"],["enforcar","A"],["favela","D"],["juízo-bobo","L"],["norte","T"],
    ["militar","P",1],["polaina","O"],["despetalar","A"],["cabresto","D"],["Oscarito","L"],["perigo","T"],
    ["Zélia Cardoso de Mello","P",1],["tangerina","O"],["descolar","A"],["cabo","D"],["LP","L"],["alçapão","T"],
    ["sanguessuga","P",1],["trena","O"],["auscultar","A"],["altruísta","D"],["Mortadelo e Salaminho","L"],["Vila Sésamo","T"],
    ["gado","P",1],["decote","O",1],["segurar","A",1],["alegria","D",1],["blefe","L",1],["lambreta","T"],
    ["buraco","P"],["farda","O"],["fazer a cama","A"],["tabelião","D"],["cineclube","L"],["cobre","T"],
    ["pardal","P",1],["escova de dentes","O"],["alvejar","A"],["cinto","D"],["quarteto de cordas","L"],["explosão atômica","T"],
    ["cova","P",1],["tubo de ensaio","O"],["pousar","A"],["delegacia","D"],["\"Columbo\"","L"],["sal","T"],
    ["amante","P",1],["réstia","O",1],["selar","A",1],["bomba atômica","D",1],["Choro (música)","L",1],["caminho","T"],
    ["imperador","P",1],["jaqueta","O"],["oferecer","A"],["coletivo","D"],["Broadway","L",1],["forno","T"],
    ["gavião","P",1],["vitrô","O",1],["canalizar","A"],["parlamentarismo","D"],["\"Sombra, Guerra e Água Fresca\"","L"],["mês","T"],
    ["tribo","P",1],["artéria","O"],["assinar","A"],["chofer","D"],["joystick","L"],["peneira","T"],
    ["caramanchão","P",1],["bicicleta","O"],["agonizar","A"],["item","D",1],["FIFA","L"],["escuro","T"],
    ["herbívoro","P",1],["bolo de casamento","O",1],["dar um tempo","A",1],["danos","D",1],["Nelson Ned","L",1],["retorno","T"],
    ["malandro","P",1],["tapiscira","O",1],["despertar","A",1],["acervo","D",1],["literatura","L"],["espírito","T"],
    ["grego","P",1],["moeda","O",1],["abridor de garrafas","A",1],["outono","D"],["Zé do Caixão","L"],["futuro","T"],
    ["intestino","P",1],["azulejo","O"],["fuxilar","A"],["férias","D"],["hóquei no gelo","L"],["baixela de prata","T"],
    ["Boris Yeltsin","P",1],["zurzido","O"],["fuzilar","A"],["cachaça","D"],["Cazuza","L"],["xampu","T"],
    ["fraco","P",1],["pregador (de roupas)","O",1],["desunir","A",1],["viés","D",1],["\"Os Simpsons\"","L",1],["manta","T"],
    ["mercado","P"],["botão de rosa","O"],["derramar","A"],["genocídio","D"],["\"Escolinha do Professor Raimundo\"","L"],["neblina","T"],
    ["marajá","P",1],["espinha de peixe","O"],["estender os braços","A"],["arapuca","D"],["flauta","L"],["congestionamento","T"],
    ["músico","P",1],["anzol","O"],["datar","A"],["informação","D"],["FM","L"],["corrimão","T"],
    ["nissei","P",1],["palanque","O"],["datar","A"],["fiador","D"],["música sertaneja","L"],["troco","T"],
    ["altar","P",1],["pau da barraca","O",1],["aliança","A",1],["\"Macunaíma\"","D",1],["direita","L",1],["raiz","T"],
    ["quadrilha","P"],["bisnaga","O"],["contar um segredo","A"],["amigo","D"],["full house","L"],["remédio","T"],
    ["índio","P",1],["grafite","O"],["lapidar","A"],["orvalho","D"],["Obelix","L"],["cantil","T"],
    ["meio-fio","P",1],["represa","O"],["colorir","A"],["hediondo","D"],["\"Sociedade dos Poetas Mortos\"","L"],["Taça Jules Rimet","T"],
    ["Alá","P",1],["louça","O"],["repartir","A"],["incenso","D"],["\"As Minas do Rei Salomão\"","L"],["oráculo","T"],
    ["imundo","P",1],["presilha","O",1],["classificar","A",1],["carvalho","D",1],["goleiro","L",1],["gin","T"],
    ["burro","P"],["adesivo","O"],["engarrafar","A"],["bola de rúgbi","D"],["engradado","L"],["chorão","T"],
    ["jamanta","P",1],["prender","O"],["célebre","A"],["arquibancada","D"],["biblioteca","L"],["chorão","T"],
    ["iluminado","P",1],["jangada","O"],["abaixar","A"],["obra-prima","D"],["luta livre","L"],["prensa","T"],
    ["pai-de-santo","P",1],["baforada","O"],["inaugurar","A"],["mal-entendido","D"],["rap","L"],["tape-deck","T"],
    ["pinto","P",1],["castelo de areia","O",1],["rebolar","A",1],["barbeiragem","D",1],["\"A Dança dos Vampiros\"","L",1],["orla","T"],

    // --- Batch 4 ---
    ["xá","P"],["cálice","O"],["flertar","A"],["irreversível","D"],["gol de empate","L",1],["petisco","T"],
    ["Onassis","P"],["estetoscópio","O"],["cutucar","A"],["rasilho","D"],["recreio","L"],["carroça de boi","T"],
    ["garça","P"],["cristaleira","O"],["caçoar","A"],["cirroso","D"],["\"A Praça da Alegria\"","L",1],["Arquimedes","T"],
    ["camelô","P"],["rojão","O"],["girar","A"],["\"A Ponte do Rio Kwai\"","D"],["Mercedes Sosa","L"],["atrito","T"],
    ["cuatinga","P"],["filé (carne)","O"],["cuidar","A"],["peça","D"],["goteira","T"],
    ["centro","P"],["galinheiro","O"],["vibrar","A"],["zumbido","D"],["reggae","L"],["cúmulo (nuvem)","T"],
    ["tromba (de elefante)","P"],["balsa","O"],["lecionar","A"],["alça","D",1],["arte abstrata","L",1],["gravata borboleta","T"],
    ["filósofo","P"],["vestido","O"],["digitar","A"],["freguês","D"],["Imagem & Ação","L",1],["sola","T"],
    ["gruta","P"],["cacho de bananas","O"],["alcançar","A"],["judeu","D"],["acrobacia aérea","L",1],["prova","T"],
    ["mina","P",1],["faro","O",1],["aguar","A",1],["debutante","D",1],["Mussum","L",1],["volante","T"],
    ["penhasco","P",1],["gaita","O"],["pedalar","A"],["necessidade","D"],["Vinicius de Moraes","L"],["coice","T"],
    ["nadador","P"],["compasso","O"],["desabrochar","A",1],["jogral","D"],["Chacrinha","L"],["pé-sapo","T"],
    ["sítio","P"],["algodão doce","O"],["aspirar o pó","A",1],["vidente","D"],["Bolinha","L"],["barba-rama","T"],
    ["corte no braço","P"],["plugue","O"],["emendar","A"],["macunha","D"],["bolinha de gude","L",1],["barril","T"],
    ["anormal","P",1],["curativo","O"],["doar","A"],["vizinho","D"],["velejar","L"],["comício","T"],
    ["grávida","P",1],["capela","O"],["abanar o rabo","A"],["cafajeste","D"],["karaokê","L",1],["maria-mole","T"],
    ["João-de-barro","P"],["pé-de-coelho","O"],["jogar videogame","A",1],["ninfomaníaca","D",1],["bola de tênis","L"],["incêndio","T"],
    ["Serra Pelada","P",1],["garrafão","O"],["plantar bananeira","A",1],["horário","D"],["Fernando Sabino","L"],["McDonald's","T"],
    ["ladeira","P"],["sarcófago","O"],["esbravejar","A"],["tribuna","D"],["festa de aniversário","L",1],["ameixa","T"],
    ["pedicuro","P"],["aquarela","O"],["listar","A"],["cinismo","D"],["\"Corra Que a Polícia Vem Aí\"","L",1],["rastro","T"],
    ["Galileu Galilei","P",1],["estátua","O"],["mutilar","A"],["vinagre","D"],["Faustão","L",1],["crédito","T"],
    ["raquítico","P",1],["valar","O",1],["vaiar","A",1],["líbido","D",1],["desafinado","L",1],["amor","T"],
    ["China","P",1],["pedestal","O",1],["coletar lixo","A",1],["calibre","D",1],["\"Robin Hood\"","L",1],["cinto","T"],
    ["pixaim","P",1],["luneta","O",1],["anular","A",1],["pneumonia","D",1],["concurso de beleza","L",1],["apartheid","T"],
    ["travesti","P",1],["privada","O",1],["tossir","A",1],["carburador (de automóvel)","D",1],["fogos de artifício","L",1],["piteira","T"],
    ["fígado","P"],["juba","O"],["cruzar","A",1],["pó","D"],["concurso de calouros","L"],["saco","T"],
    ["planície","P"],["capanga (bolsa)","O"],["colocar","A"],["\"Meu Pé de Laranja Lima\"","D",1],["arranhão","L"],["diligência","T"],
    ["samurai","P",1],["tear","O"],["estagiar","A"],["habitante","D"],["\"Os Intocáveis\"","L",1],["diligência","T"],
    ["bangalô","P"],["poço","O"],["arrepiar cabelos","A",1],["fotossíntese","D",1],["Pepe Legal","L"],["frango assado","T"],
    ["relator","P",1],["estornudo","O",1],["cuspir","A",1],["clorofila","D",1],["\"Guerra e Paz\"","L",1],["caroço","T"],
    ["pigmeu","P"],["chafariz","O"],["comunicar","A"],["sósia","D"],["\"Boatinha Mas Ordinária\"","L"],["miolo","T"],
    ["escorpião","P"],["defunto","O"],["aplicar injeção","A"],["higiene","D"],["esqui aquático","L",1],["tatuagem","T"],
    ["Pedro Álvares Cabral","P"],["pente","O"],["encalhar","A"],["apocalipse","D"],["\"Os Brutos Também Amam\"","L",1],["Florianópolis","T"],
    ["Taj Mahal","P",1],["gelo","O"],["criar","A"],["sangria","D"],["campeão","L"],["molho de chaves","T"],
    ["usina","P",1],["fita isolante","O",1],["sambar","A",1],["sprenguiça","D",1],["Pato Donald","L",1],["lixo","T"],
    ["quente","P"],["chuveiro","O"],["semear","A"],["ébrio","D"],["Sérgio Mallandro","L"],["política salarial","T"],
    ["Uruguai","P"],["pajé","O"],["mumificar","A"],["vítima","D"],["pular do trampolim","L",1],["mira","T"],
    ["ema","P"],["cacho de uva","O"],["encaçapar","A",1],["viscoso","D"],["\"Flash Gordon\"","L"],["panela","T"],
    ["oca","P",1],["máscara de mergulho","O"],["sofrer","A"],["interessante","D"],["\"Sete Velhos Para Sete Irmãos\"","L",1],["mole","T"],
    ["Arizona","P"],["caneta-tinteiro","O"],["chamar","A"],["hadalar","D",1],["Bidu","L"],["fusca","T"],
    ["recepção","P"],["carro de bombeiros","O"],["ponteiro de relógio","A"],["atrelar","D"],["epidemia","L",1],["trinca","T"],
    ["Albert Einstein","P",1],["laçar","O"],["abandonar","A"],["quartzo","D"],["CD","L"],["guilhotina","T"],
    ["açougue","P",1],["tacho","O"],["bípede","D"],["\"Os Dez Mandamentos\"","L",1],["goma","T"],
    ["pastor","P"],["caminhão basculante","O"],["embalsamar","A"],["inibição","D"],["Pernalonga","L"],["frase","T"],
    ["Carlos Drummond de Andrade","P",1],["pipoca","O"],["vomitar","A"],["toxina","D"],["\"Os Jetsons\"","L",1],["pinha","T"],
    ["agenda","P",1],["limpar","O"],["espiar","A"],["\"O Vigilante Rodoviário\"","D",1],["lombriga","L"],
    ["cavalo-do-mar","P"],["caixa de som","O"],["taxiar","A"],["adoção","D"],["trem-fantasma","L",1],["moda","T"],
    ["sentinela","P",1],["para-quedas","O"],["refletir","A"],["ontem","D"],["surfe","L"],
    ["ladrão","P"],["favo","O"],["rodar","A"],["liberal","D"],["\"Por Quem os Sinos Dobram\"","L",1],["solidão","T"],

    // --- Batch 5 ---
    ["penico","O"],["amontoar","A"],["reumatismo","D"],["Cinema Novo","L",1],["estetoscópio","T"],
    ["balneário","P"],["porteira","O"],["rosquear","A",1],["amargo","D"],["autorama","L"],["nêutron","T"],
    ["perna","P"],["desentupidor de pia","O"],["calejar","A",1],["felicidade","D"],["esqui na neve","L"],["propaganda","T"],
    ["Falcão (jogador)","P",1],["figurinha","O"],["investigar","A"],["casebre","D"],["manilha","L"],["Exército","T"],
    ["golfinho","P"],["mobile","O",1],["arremeter","A"],["hipócrita","D"],["Sean Connery","L"],["páreo","T"],
    ["canibal","P",1],["bico","O"],["pendurar","A"],["odalisca","D"],["\"Tartarugas Ninja\"","L",1],["tina","T"],
    ["vila","P"],["quintal","O"],["segurança","A"],["Paco de Lucía","D"],["sabor","L"],["dilatar","T"],
    ["hábito","P",1],["violão","O"],["adormecer","A"],["trame","D"],["\"Gremlins\"","L"],["prefeitura","T"],
    ["motorista","P"],["crachá","O"],["desmontar","A"],["argola","D"],["Mandrake","L"],["pólvora","T"],
    ["escravo","P"],["empilhadeira","O"],["abrir","A",1],["barulho","D"],["\"Frankenstein\"","L"],["painel","T"],
    ["poderoso","P"],["triciclo","O"],["desfilar","A"],["paquera","D",1],["artista","L"],["maiô","T"],
    ["mudo","P"],["retroprojetor","O"],["calçar sapatos","A"],["radical","D"],["Van Gogh","L"],["olhar","T"],
    ["California","P"],["garrafa térmica","O"],["deslizar","A"],["purgatório","D"],["Oscar","L"],["perdão","T"],
    ["coxa","P",1],["furadeira","O"],["caber","A"],["hangar","D"],["croupier","L"],["indústria","T"],
    ["careca","P"],["rolha","O"],["agradecer","A"],["xifópago","D"],["florete (de esgrima)","L"],["brasão","T"],
    ["serralheiro","P",1],["fenda","O"],["imitar","A"],["nicho","D"],["baile de máscaras","L"],["anúncio de jornal","T"],
    ["dark","P"],["cinto de castidade","O"],["tocar violão","A"],["analfabeto","D"],["\"O Último Imperador\"","L"],["vídeo","T"],
    ["Charles Darwin","P",1],["broca","O"],["riscar","A"],["chimarrão","D"],["bateria","L"],["ovo de codorna","T"],
    ["humor","P",1],["aerófilo","O"],["soltar rojões","A"],["vadiagem","D"],["cenografia","L"],["óleo","T"],
    ["pororoca","P",1],["talheres","O"],["mudar o curso","A"],["bordel","D"],["mímica","L"],["lotação","T"],
    ["Berlim","P"],["fita de vídeo","O"],["benzer","A"],["câmara de gás","D"],["Frank Sinatra","L"],["microscópio","T"],
    ["torto","P"],["escova de cabelo","O"],["incendiar","A",1],["marcapasso","D"],["aeróbica","L"],["paladar","T"],
    ["João Havelange","P"],["bacia","O"],["bordar","A"],["inverno","D"],["patinação no gelo","L"],["nascimento","T"],
    ["piranha","P",1],["conta (de restaurante)","O"],["encher linguiça","A"],["vínculo","D"],["ficção científica","L"],["proa","T"],
    ["invisível","P"],["poleiro","O"],["cachear","A"],["coroa funerária","D"],["\"O Exorcista\"","L"],["palheta","T"],
    ["mago","P"],["carnê","O"],["vingança","A",1],["Mickey","D"],["tora","L"],["sabão","T"],
    ["praça","P"],["arpão","O"],["respirar fundo","A",1],["acelerador","D"],["bater um recorde","L"],["lacre","T"],
    ["Urano","P"],["beliche","O"],["ir contra a maré","A",1],["tribunal","D"],["\"Nacional Kid\"","L"],["limão","T"],
    ["Oiapoque","P",1],["espeto","O"],["batizar","A"],["chave inglesa","D"],["Gato Félix","L"],["querosene","T"],
    ["risada","P"],["quebra-nozes","O",1],["chupar","A"],["breu","D",1],["conjunto de rock","L"],
    ["ameba","P"],["prendedor de gravata","O",1],["gesticular","A"],["pasta de dentes","D"],["Emerson Fittipaldi","L"],["maré","T"],
    ["Mikhail Gorbachev","P"],["cipó","O",1],["penetrar","A"],["quilo","D"],["engolidor de espadas","L"],["vista","T"],
    ["inteligência","P"],["faísca elétrica","O"],["ditar","A"],["virgem","D"],["blues","L"],["natureza-morta","T"],
    ["opaco","P",1],["frigideira","O"],["bueiro entupido","D"],["\"Os Sertões\"","L"],["milagre","T"],
    ["quina","P"],["chapeleira","O",1],["passar a mão","A"],["carinho","D"],["festival de música","L"],["sufoco","T"],
    ["Manaus","P"],["cuecas","O"],["envelopar","A",1],["manifestação","D"],["Saci Pererê","L"],["tampa","T"],
    ["farol (de praia)","P"],["cadeira de praia","O",1],["andar descalço","A"],["inodoro","D"],["Tom Cruise","L"],["Aeronáutica","T"],
    ["Jânio Quadros","P",1],["documento de identidade","O"],["borrifar","A"],["dormente (de trem)","D"],["par-ou-ímpar","L"],["ortogonal","T"],
    ["escama","P",1],["guarita","O"],["envelhecer","A"],["voraz","D"],["\"O Exterminador do Futuro\"","L"],["palmito","T"],
    ["malhado","P",1],["tomada","O"],["servir","A",1],["ficar de castigo","D"],["coreografia","L"],["assar","T"],
    ["miserável","P"],["túnel","O"],["puxar o saco","A",1],["transistor","D"],["Hollywood","L"],["parêntese","T"],
    ["feira","P",1],["jaca","O"],["acelerar","A"],["indecente","D"],["peteca","L"],["saia-balão","T"],
    ["português","P",1],["espremedor de frutas","O"],["matar","A"],["furto","D"],["recital","L"],["poço sem fundo","T"],
    ["corcunda","P",1],["catapulta","O"],["umedecer","A"],["esmola","D"],["Grande Otelo","L"],["Coca-Cola","T"],
    ["pés-descalços","P",1],["prato","O"],["destampar","A",1],["estrangular","D"],["exposição","L"],["Torre de Pisa","T"],
    ["prostituta","P"],["broche","O"],["mastigar","A",1],["censura","D"],["solista","L"],["março","T"],
    ["oriente","P"],["dentadura","O"],["abençoar","A",1],["vidro estilhaçado","D"],["Inspetor Clouseau","L"],["rota","T"],
    ["urubu","P"],["fruteira","O"],["enxergar","A"],["cabeleireiro","D"],["Picasso","L"],["mato","T"],
    ["piolho","P"],["picolé","O"],["manobrar","A"],["corja","D"],["equilibrista","L"],["forquilha","T"],
    ["subterrâneo","P"],["bom-bocado","O",1],["morar","A"],["curso","D"],["\"Jaspion\"","L"],["monitor","T"],

    // --- Batch 6 ---
    ["marinheiro","P",1],["depilador","O"],["pegar fogo","A"],["tragédia","D"],["bola sete","L"],["popa","T"],
    ["Xingu","P"],["coifa","O"],["remar contra a maré","A"],["hipoteca","D"],["\"A Mosca\"","L",1],["azeitona","T"],
    ["psicótico","P",1],["cinta-liga","O"],["remendar","A"],["estivador","D"],["Maguila","L"],["pesquisa","T"],
    ["alquimista","P"],["terno","O",1],["telegrafar","A"],["cabide de empregos","D"],["João Gilberto","L"],["além","T"],
    ["longitude","P",1],["guarda-roupa","O"],["acusar","A"],["fábula","D"],["Museu de Cera","L"],["estrela de Belém","T"],
    ["boteco","P"],["outdoor","O"],["assustar","A"],["xucro","D"],["bolero","L"],["canal","T"],
    ["camaleão","P"],["macarronada","O"],["mudar de casa","A"],["verdade","D"],["\"Os Canhões de Navarone\"","L"],["vatapá","T"],
    ["chalé","P"],["disquete","O"],["cabecear (bola)","A"],["maníaco","D"],["Arrelia","L"],["satélite","T"],
    ["Leonel Brizola","P"],["botijão de gás","O"],["cerzir","A"],["mio","D"],["\"Viagem ao Centro da Terra\"","L"],["próton","T"],
    ["mão","P",1],["grampo (de cabelo)","O"],["esfaquear","A"],["reserva indígena","D"],["Boris Karloff","L"],["\"Bumba Meu Boi\"","T"],
    ["Recife","P",1],["aerossol","O"],["soltar os cachorros","A"],["ambição","D"],["João Saldanha","L"],["alho","T"],
    ["maluco","P"],["cartucheira","O"],["amanhecer","A"],["capacidade","D"],["Juca Chaves","L"],["carreata","T"],
    ["rabo","P"],["caixote","O"],["fritar ovo","A"],["barganha","D"],["Marcello Mastroianni","L"],["paralela","T"],
    ["negro","P",1],["mala","O"],["operar uma máquina","A"],["caderneta de poupança","D"],["mágico","L"],["berimbau","T"],
    ["estrada","P",1],["macacão","O"],["trabalhar","A"],["camarada","D"],["dupla sertaneja","L",1],["luxo","T"],
    ["Holanda","P",1],["jardineira","O"],["socorrer","A"],["nunca","D"],["cartão amarelo","L"],["páscoa","T"],
    ["homossexual","P",1],["adega","O"],["degustar","A"],["falência","D"],["cordel","L"],["polia","T"],
    ["perto","P"],["banheira","O"],["debruçar","A"],["caminhada","D"],["\"Casablanca\"","L"],["picada","T"],
    ["faquir","P"],["mata-borrão","O"],["aparafusar","A"],["repartição","D"],["King (jogo de cartas)","L"],["muro","T"],
    ["ornitorrinco","P",1],["colcha","O"],["desgarrar-se do rebanho","A",1],["abertura","D"],["\"Lawrence da Arábia\"","L"],["senado","T"],
    ["casal","P",1],["espiga de milho","O"],["bater bola","A"],["guru","D"],["dormir na rede","L"],["prótese","T"],
    ["galã","P",1],["tridente","O"],["passear","A"],["salada de frutas","D"],["Clarabela e Horácio","L"],["caipirinha","T"],
    ["fêmea","P"],["cocheira","O"],["arregaçar as mangas","A"],["vestibular","D"],["Tio Patinhas","L",1],["barro","T"],
    ["oficina","P"],["carteira escolar","O"],["emborrachar","A"],["combustão","D"],["\"A Família Adams\"","L"],["bebida","T"],
    ["macaco","P"],["estepe","O"],["estacionar o carro","A"],["trote","D"],["coreto","L"],["hipnose","T"],
    ["cérebro","P",1],["bolsa","O"],["dar ponto sem nó","A"],["democracia","D"],["piano de cauda","L"],["diamante","T"],
    ["jacaré","P",1],["astro","O"],["botar pra quebrar","A"],["conto-do-vigário","D"],["\"Os Três Patetas\"","L"],["gângster","T"],
    ["maloca","P"],["bengala","O"],["deixar cair","A"],["singelo","D"],["beque","L"],["tanque de guerra","T"],
    ["Richard Nixon","P",1],["guache","O"],["afundar","A"],["cúpula","D"],["Mangueira (escola de samba)","L"],["vasectomia","T"],
    ["salva-vidas","P"],["fusível","O"],["equilibrar","A"],["comunismo","D"],["basquetebol","L"],["porta-níqueis","T"],
    ["ministro","P",1],["beiral","O"],["assistir à TV","A"],["útero","D"],["jogar os dados","L"],["reação","T"],
    ["milharal","P",1],["dedal","O"],["cair","A"],["burguesia","D"],["baile","L"],["manchete","T"],
    ["bilheteria","P"],["rastelo","O"],["encostar","A"],["bisbilhoteira","D"],["Manda-Chuva","L"],["radioativo","T"],
    ["locutor","P",1],["soja","O"],["atravessar a nado","A"],["rodapé","D"],["Olívia Palito","L"],["fração","T"],
    ["funcionário","P"],["timão","O",1],["ventilar","A"],["ecologia","D"],["\"A Última Ceia\"","L"],["ogiva","T"],
    ["vespa","P",1],["pé-de-pato","O"],["enganar","A"],["profeta","D"],["bola na rede","L"],["maço de cigarros","T"],
    ["Getúlio Vargas","P",1],["microondas","O"],["trocar óleo","A"],["formol","D"],["Homem Aranha","L"],["Belém","T"],
    ["tuiuiú","P"],["tapete","O"],["plantar","A"],["pomba","D"],["Fernando Pessoa","L"],["calor","T"],
    ["réptil","P"],["calculadora","O"],["subir","A"],["verbo","D"],["Búfalo Bill","L"],["órgão","T"],
    ["DNA","P"],["moldura","O"],["assoar","A"],["voto nulo","D"],["Pierrô","L"],["rápido","T"],
    ["terrorista","P",1],["carruagem","O"],["filmar","A",1],["sociodrama","D"],["hora da verdade","L"],["transfusão","T"],
    ["córrego","P"],["alicate","O",1],["expor","A"],["hospício","D"],["Saninho","L"],["lobisomem","T"],
    ["Aristóteles","P",1],["espingarda","O"],["Fafá de Belém","D"],["pano","L"],["cuíca","T"],
    ["culote","P"],["trono","O"],["AIDS","D"],["Zé do Boné","L"],["interrogatório","T"],
    ["mico-leão","P",1],["adaga","O"],["cambalear","A"],["mexerico","D"],["fogueira de São João","L"],["invenção","T"],
    ["ouriço","P",1],["enceradeira","O"],["marcar a ferro","A"],["dedo-duro","D"],["lá (nota)","L"],["transferidor (régua)","T"],
  ];

  const seen = new Set();
  const out = [];
  for (const entry of RAW) {
    const word = entry[0];
    const category = entry[1];
    if (!word || word.trim() === "") continue;
    const allPlay = category === "T" ? true : Boolean(entry[2]);
    const key = word.toLowerCase() + "|" + category;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ word: word, category: category, allPlay: allPlay });
  }
  window.MIMIC_WORDS = out;
})();
